/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10
terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 
*/

/*Psuedocode
set term 1 and 2 to 1

While term 2 < 4,000,000
    temp = term 2
    term 2 = term 1 + term 2
    term 1 = temp

    if term 2 % 2 == 0
    sum += term 2

*/
#include <iostream>

int main()
{
    int termOne = 1;
    int termTwo = 1;
    int temp;
    int sum = 0;

    while(termTwo < 4000000)
    {
        temp = termTwo;
        termTwo = termOne + termTwo;
        termOne = temp;

        if(termTwo % 2 == 0)
        {
            sum += termTwo;
        }    
    }

    std::cout << sum << std::endl;
}